version: '3.9'

services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - ./laravel:/var/www/html
    user: "${UID}:${GID}"
    depends_on:
      - db
    networks:
      - laravel

  web:
    image: nginx:stable
    container_name: laravel_web
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

networks:
  laravel:

volumes:
  pgdata: